# Generated by Django 3.2 on 2021-05-02 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_strategy_viewset'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='bet_pl',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
    ]
