# Generated by Django 3.2 on 2021-05-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='viewset_url',
            field=models.CharField(default='api', max_length=32),
        ),
    ]
